# Generated by Django 4.1 on 2023-03-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
