# Generated by Django 4.1 on 2023-03-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_video_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.TextField(default=' '),
        ),
    ]
